version: '3.6'
services:
  kpi-postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./data/kuepetitionindex/db:/var/lib/postgresql/data
      - ./docker/kuepetitionindex/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports: 
      - "5897:5432"
    container_name: kpi-postgres
  hasura-kuepetitionindex-backend:
    image: hasura/graphql-engine:v2.8.3
    ports:
    - "8097:8080"
    container_name: hasura-kuepetitionindex-backend
    depends_on:
    - "kpi-postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_METADATA_DATABASE_URL}
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: ${PG_DATABASE_URL}
      HASURA_GRAPHQL_DATABASE_URL: ${PG_DATABASE_URL}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "${JWT_SECRET_KEY}"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
